require: rubocop-rails

AllCops:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/posts_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'bin/setup'
    - 'bin/update'
    - 'config/application.rb'
    - 'db/migrate/20170526114520_create_posts.rb'
    - 'spec/controllers/post_controllers_spec.rb'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'

