language: ruby
dist: trusty
rvm:
  - 2.6
  - truffleruby

services:
  - postgresql

script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
